# Generated by Django 5.2.4 on 2025-08-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('service', models.CharField(blank=True, max_length=120)),
                ('audience_type', models.CharField(choices=[('customer_inquiry', 'Customer Inquiry'), ('general_question', 'General Question'), ('other_inquiry', 'Other Inquiry'), ('partnership', 'Partnership Opportunity'), ('feedback', 'Feedback Request')], default='customer_inquiry', max_length=32)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
